# Copyright 2026 Thomson Reuters
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if and .Values.config.originVerification.enabled (eq .Values.config.originVerification.strategy "externalSecret") }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-origin-verify" (include "gate.fullname" .) }}
  labels:
    {{- include "gate.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.config.originVerification.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ if .Values.externalSecrets.secretStore.create }}{{ .Values.externalSecrets.secretStore.name }}{{ else }}{{ .Values.config.originVerification.externalSecret.secretStoreName }}{{ end }}
    kind: SecretStore
  target:
    name: {{ printf "%s-origin-verify" (include "gate.fullname" .) }}
    creationPolicy: Owner
    template:
      metadata:
        labels:
          {{- include "gate.labels" . | nindent 10 }}
  data:
    - secretKey: value
      remoteRef:
        key: {{ .Values.config.originVerification.externalSecret.remoteSecretName }}
{{- end }}
