# Copyright 2026 Thomson Reuters
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if and (eq .Values.config.githubApps.strategy "externalSecret") .Values.externalSecrets.secretStore.create }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStore.name }}
  labels:
    {{- include "gate.labels" . | nindent 4 }}
  {{- with .Values.externalSecrets.secretStore.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  provider:
    {{- if eq .Values.externalSecrets.secretStore.provider.type "aws" }}
    aws:
      service: {{ .Values.externalSecrets.secretStore.provider.aws.service }}
      region: {{ .Values.externalSecrets.secretStore.provider.aws.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "gate.serviceAccountName" . }}
    {{- else if eq .Values.externalSecrets.secretStore.provider.type "gcp" }}
    gcpsm:
      projectID: {{ .Values.externalSecrets.secretStore.provider.gcp.projectID }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.externalSecrets.secretStore.provider.gcp.clusterLocation }}
          clusterName: {{ .Values.externalSecrets.secretStore.provider.gcp.clusterName }}
          serviceAccountRef:
            name: {{ include "gate.serviceAccountName" . }}
    {{- else if eq .Values.externalSecrets.secretStore.provider.type "azure" }}
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: {{ .Values.externalSecrets.secretStore.provider.azure.vaultUrl }}
      serviceAccountRef:
        name: {{ include "gate.serviceAccountName" . }}
    {{- else if eq .Values.externalSecrets.secretStore.provider.type "vault" }}
    vault:
      server: {{ .Values.externalSecrets.secretStore.provider.vault.server }}
      path: {{ .Values.externalSecrets.secretStore.provider.vault.path }}
      version: {{ .Values.externalSecrets.secretStore.provider.vault.version | default "v2" }}
      auth:
        kubernetes:
          mountPath: {{ .Values.externalSecrets.secretStore.provider.vault.mountPath }}
          role: {{ .Values.externalSecrets.secretStore.provider.vault.role }}
          serviceAccountRef:
            name: {{ include "gate.serviceAccountName" . }}
    {{- end }}
{{- end }}
